const DATA_URL='data/portfolio-data.json';const KEY='iqoma-admin-data';const THEME_KEY='iqoma-portfolio-theme';let data;let current=0;const $=(s,p=document)=>p.querySelector(s);
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function load(){const saved=localStorage.getItem(KEY);if(saved)return JSON.parse(saved);const r=await fetch(DATA_URL,{cache:'no-store'});return r.json()}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderList();fillForm();preview()}
function initTheme(){const saved=localStorage.getItem(THEME_KEY)||'light';document.documentElement.dataset.theme=saved;const b=$('#theme-toggle');b.textContent=saved==='dark'?'Light':'Dark';b.onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem(THEME_KEY,n);b.textContent=n==='dark'?'Light':'Dark'}}
function renderList(){const list=$('#project-list');list.innerHTML=data.projects.map((p,i)=>`<button type="button" data-i="${i}">${esc(p.title)}<br><small>${esc(p.category)}</small></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=Number(b.dataset.i);fillForm();preview()})}
function fillForm(){const p=data.projects[current];const f=$('#admin-form');Object.keys(p).forEach(k=>{if(!f.elements[k])return;if(Array.isArray(p[k]))f.elements[k].value=p[k].join('\n');else f.elements[k].value=p[k]||''});}
function readForm(){const f=$('#admin-form');const p=data.projects[current]||{};['id','title','category','role','year','status','image','summary','impact','problem','goal'].forEach(k=>p[k]=f.elements[k].value);['process','solution','tools'].forEach(k=>p[k]=f.elements[k].value.split('\n').map(x=>x.trim()).filter(Boolean));return p}
function preview(){const p=readForm();$('#admin-preview').innerHTML=`<article class="project-card"><div class="project-visual">${p.image?`<img src="${esc(p.image)}">`:''}</div><div class="project-body"><span class="status-badge">${esc(p.status)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><span class="case-study-link">View case study →</span></div></article>`}
function download(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-data.json';a.click();URL.revokeObjectURL(a.href)}
async function init(){initTheme();data=await load();renderList();fillForm();preview();$('#admin-form').oninput=preview;$('#admin-form').onsubmit=e=>{e.preventDefault();data.projects[current]=readForm();save()};$('#new-project').onclick=()=>{data.projects.unshift({id:'new-project',title:'New Project',category:'Case Study',role:'Designer',year:'2026',status:'Draft',summary:'',impact:'',image:'',problem:'',goal:'',users:[],process:[],solution:[],outcome:'',tools:[]});current=0;save()};$('#delete-project').onclick=()=>{data.projects.splice(current,1);current=0;save()};$('#export-json').onclick=download}
init();
